<?php

add_action( 'init', function() {
	register_post_type( 'content-slide', array(
	'labels' => array(
		'name' => 'Content Slides',
		'singular_name' => 'Content Slide',
		'menu_name' => 'Content Slides',
		'all_items' => 'All Content Slides',
		'edit_item' => 'Edit Content Slide',
		'view_item' => 'View Content Slide',
		'view_items' => 'View Content Slides',
		'add_new_item' => 'Add New Content Slide',
		'new_item' => 'New Content Slide',
		'parent_item_colon' => 'Parent Content Slide:',
		'search_items' => 'Search Content Slides',
		'not_found' => 'No content slides found',
		'not_found_in_trash' => 'No content slides found in Trash',
		'archives' => 'Content Slide Archives',
		'attributes' => 'Content Slide Attributes',
		'insert_into_item' => 'Insert into content slide',
		'uploaded_to_this_item' => 'Uploaded to this content slide',
		'filter_items_list' => 'Filter content slides list',
		'filter_by_date' => 'Filter content slides by date',
		'items_list_navigation' => 'Content Slides list navigation',
		'items_list' => 'Content Slides list',
		'item_published' => 'Content Slide published.',
		'item_published_privately' => 'Content Slide published privately.',
		'item_reverted_to_draft' => 'Content Slide reverted to draft.',
		'item_scheduled' => 'Content Slide scheduled.',
		'item_updated' => 'Content Slide updated.',
		'item_link' => 'Content Slide Link',
		'item_link_description' => 'A link to a content slide.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-slides',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'fullpage-slide', array(
	'labels' => array(
		'name' => 'Fullpage Slides',
		'singular_name' => 'Fullpage Slide',
		'menu_name' => 'Fullpage Slides',
		'all_items' => 'All Fullpage Slides',
		'edit_item' => 'Edit Fullpage Slide',
		'view_item' => 'View Fullpage Slide',
		'view_items' => 'View Fullpage Slides',
		'add_new_item' => 'Add New Fullpage Slide',
		'new_item' => 'New Fullpage Slide',
		'parent_item_colon' => 'Parent Fullpage Slide:',
		'search_items' => 'Search Fullpage Slides',
		'not_found' => 'No fullpage slides found',
		'not_found_in_trash' => 'No fullpage slides found in Trash',
		'archives' => 'Fullpage Slide Archives',
		'attributes' => 'Fullpage Slide Attributes',
		'insert_into_item' => 'Insert into fullpage slide',
		'uploaded_to_this_item' => 'Uploaded to this fullpage slide',
		'filter_items_list' => 'Filter fullpage slides list',
		'filter_by_date' => 'Filter fullpage slides by date',
		'items_list_navigation' => 'Fullpage Slides list navigation',
		'items_list' => 'Fullpage Slides list',
		'item_published' => 'Fullpage Slide published.',
		'item_published_privately' => 'Fullpage Slide published privately.',
		'item_reverted_to_draft' => 'Fullpage Slide reverted to draft.',
		'item_scheduled' => 'Fullpage Slide scheduled.',
		'item_updated' => 'Fullpage Slide updated.',
		'item_link' => 'Fullpage Slide Link',
		'item_link_description' => 'A link to a fullpage slide.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-slides',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
	),
	'delete_with_user' => false,
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'content-slide-category', array(
	0 => 'content-slide',
), array(
	'labels' => array(
		'name' => 'Content Slide Categories',
		'singular_name' => 'Content Slide Category',
		'menu_name' => 'Content Slide Categories',
		'all_items' => 'All Content Slide Categories',
		'edit_item' => 'Edit Content Slide Category',
		'view_item' => 'View Content Slide Category',
		'update_item' => 'Update Content Slide Category',
		'add_new_item' => 'Add New Content Slide Category',
		'new_item_name' => 'New Content Slide Category Name',
		'search_items' => 'Search Content Slide Categories',
		'popular_items' => 'Popular Content Slide Categories',
		'separate_items_with_commas' => 'Separate content slide categories with commas',
		'add_or_remove_items' => 'Add or remove content slide categories',
		'choose_from_most_used' => 'Choose from the most used content slide categories',
		'not_found' => 'No content slide categories found',
		'no_terms' => 'No content slide categories',
		'items_list_navigation' => 'Content Slide Categories list navigation',
		'items_list' => 'Content Slide Categories list',
		'back_to_items' => '← Go to content slide categories',
		'item_link' => 'Content Slide Category Link',
		'item_link_description' => 'A link to a content slide category',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

