<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5ee1f51590dbb',
	'title' => '[Page] Fullpage Slider',
	'fields' => array(
		array(
			'key' => 'field_5ee1f6fd18e4f',
			'label' => 'General',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee1f527e30f2',
			'label' => 'Loop Top',
			'name' => 'slider_loop_top',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ee1f54be30f3',
			'label' => 'Loop Bottom',
			'name' => 'slider_loop_bottom',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ee1f557e30f4',
			'label' => 'Speed',
			'name' => 'slider_speed',
			'aria-label' => '',
			'type' => 'range',
			'instructions' => 'Speed in ms.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 100,
			'max' => 10000,
			'step' => 100,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5ee1f70718e50',
			'label' => 'Design',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee1f588e30f5',
			'label' => 'Progress Bar',
			'name' => 'slider_progress_bar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
		),
		array(
			'key' => 'field_6714d81cefb31',
			'label' => 'Onepage Navigation',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6714d830efb32',
			'label' => 'Onepage Navigation',
			'name' => 'onepage_navigation',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Enable',
			'ui_off_text' => 'Disable',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_template',
				'operator' => '==',
				'value' => 'template-fullpage-slider.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5bc26122a92ad',
	'title' => '[Page] Overrides',
	'fields' => array(
		array(
			'key' => 'field_5bc318c304751',
			'label' => 'Navigation',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bc26126286c2',
			'label' => 'Custom Navigation',
			'name' => 'page_custom_navigation',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5bc33c5551a6c',
			'label' => 'Navigation Show',
			'name' => 'navigation_show',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3406c8a592',
			'label' => 'Navigation Type',
			'name' => 'navigation_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Default',
				'bar' => 'Bars',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3a717dfaa9',
			'label' => 'Navigation Opaque',
			'name' => 'navigation_opaque',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
					array(
						'field' => 'field_5bc3406c8a592',
						'operator' => '!=',
						'value' => 'bars',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3a769dfaac',
			'label' => 'Transparent',
			'name' => 'navigation_transparent',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3a788dfaad',
			'label' => 'Transparent Always',
			'name' => 'navigation_transparent_always',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
					array(
						'field' => 'field_5bc3406c8a592',
						'operator' => '==',
						'value' => 'bars',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3a7a1dfaae',
			'label' => 'Sticky',
			'name' => 'navigation_sticky',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
					array(
						'field' => 'field_5bc3406c8a592',
						'operator' => '==',
						'value' => 'bars',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc3a7b4dfaaf',
			'label' => 'Hide on Scroll',
			'name' => 'navigation_hide_on_scroll',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc26126286c2',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc33c5551a6c',
						'operator' => '==',
						'value' => 'show',
					),
					array(
						'field' => 'field_5bc3a7a1dfaae',
						'operator' => '==',
						'value' => 'enable',
					),
					array(
						'field' => 'field_5bc3406c8a592',
						'operator' => '!=',
						'value' => 'bar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc31a3995664',
			'label' => 'Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bc31a7895666',
			'label' => 'Custom Footer',
			'name' => 'page_custom_footer',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5bc31aef95668',
			'label' => 'Footer Show',
			'name' => 'footer_show',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc31a7895666',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5be6a77d19ddc',
			'label' => 'Footer Template',
			'name' => 'footer_template',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc31a7895666',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc31aef95668',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'Select a Template',
				6 => 'Default Kit',
				1892 => '[Subscribe Form] Subscribe Form 05',
				1580 => '[Megamenu] Contact',
				1469 => '[ADS] Wide Banner 02',
				1397 => '[Subscribe Form] Subscribe Form 04',
				1342 => '[Subscribe Form] Subscribe Form 03',
				1280 => '[ADS] Wide Banner 01',
				1158 => '[Subscribe Form] Subscribe Form 02',
				1105 => '[Page] Author',
				807 => '[Megamenu] Posts',
				797 => '[Megamenu] Categories',
				608 => '[Footer] Subscribe Light',
				211 => '[Pricing Table] Button',
				123 => '[Footer] Subscribe',
				117 => '[Footer] Minimal',
				109 => '[Page] Favorite',
				101 => '[Page] Search Results',
				87 => '[Subscribe Form] Subscribe Form 01',
				73 => '[Footer] Default',
				64 => '[Instagram] Layout 01',
				1540 => 'Default Kit',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bc31ab095667',
			'label' => 'Footer Fixed',
			'name' => 'footer_fixed',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bc31a7895666',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5bc31aef95668',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'enable' => 'Enable',
				'disable' => 'Disable',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bcf4fc2afa51',
			'label' => 'Site Protection',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bcf4fd2afa52',
			'label' => 'Custom Site Protection',
			'name' => 'page_custom_site_protection',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5bcf4ff1afa53',
			'label' => 'Site Protection',
			'name' => 'site_protection',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5bcf4fd2afa52',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'modified' => 1706960302,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5eeb56ea53c7e',
	'title' => '[Post Format] Audio',
	'fields' => array(
		array(
			'key' => 'field_5eeb56f9952f3',
			'label' => 'Audio Link',
			'name' => 'post_audio_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Input your audio link here. Here are all the supported audio formats: <br>
<a href="https://wordpress.org/support/article/audio-shortcode/#options" target="_blank">https://wordpress.org/support/article/audio-shortcode/#options</a><br>
<a href="https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from" target="_blank">https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'audio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => 1592483372,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5eeb5caba19cf',
	'title' => '[Post Format] Video',
	'fields' => array(
		array(
			'key' => 'field_5eeb5caba7e0a',
			'label' => 'Video Link',
			'name' => 'post_video_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Input your video link here. Here are all the supported video formats: <br>
<a href="https://wordpress.org/support/article/video-shortcode/#options" target="_blank">https://wordpress.org/support/article/video-shortcode/#options</a><br>
<a href="https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from" target="_blank">https://wordpress.org/support/article/embeds/#okay-so-what-sites-can-i-embed-from</a>',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_format',
				'operator' => '==',
				'value' => 'video',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => 1592483266,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5bab4215775a6',
	'title' => '[Post] Single Post',
	'fields' => array(
		array(
			'key' => 'field_5f3a282020a0f',
			'label' => 'Navigation',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f3a283020a10',
			'label' => 'Custom Navigation',
			'name' => 'post_custom_navigation',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f3a285e20a11',
			'label' => 'Post Navigation',
			'name' => 'post_navigation',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a283020a10',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f3a289f20a12',
			'label' => 'Navigation Style',
			'name' => 'post_navigation_style',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a283020a10',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5f3a285e20a11',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style-1' => 'Style 1',
				'style-2' => 'Style 2',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'modified' => 1708421782,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f3a91a410a01',
	'title' => '[Post] Single Work',
	'fields' => array(
		array(
			'key' => 'field_67447d0eb9b78',
			'label' => 'General',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_67447d1ab9b79',
			'label' => 'Excerpt',
			'name' => 'work_excerpt',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5f3a91a4183d0',
			'label' => 'Navigation',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f3a91a4183da',
			'label' => 'Custom Navigation',
			'name' => 'work_custom_navigation',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f3a91a4183e2',
			'label' => 'Work Navigation',
			'name' => 'work_navigation',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a91a4183da',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f3a91a4183ea',
			'label' => 'Navigation Style',
			'name' => 'work_navigation_style',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f3a91a4183da',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_5f3a91a4183e2',
						'operator' => '==',
						'value' => 'show',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style-1' => 'Style 1',
				'style-2' => 'Style 2',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5ee1fa8a0b277',
	'title' => '[Slide] Fullpage Slide',
	'fields' => array(
		array(
			'key' => 'field_5ee1fe56990fd',
			'label' => 'Style',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee1fabd74b44',
			'label' => 'Background Color',
			'name' => 'section_background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => false,
			'return_format' => 'string',
		),
		array(
			'key' => 'field_5ee1fd5a79a69',
			'label' => 'Background Image',
			'name' => 'section_background_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 1920,
			'min_height' => 1080,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ee5d021d7901',
			'label' => 'Ken Burn Background',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee5d032d7902',
			'label' => 'Background Image',
			'name' => 'ken_burn_background_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 1920,
			'min_height' => 1080,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f3fc299a58cf',
			'label' => 'Video Background',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f3fc2b0a58d0',
			'label' => 'Video Background',
			'name' => 'video_background',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'URL to YouTube / Vimeo video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5ee1fe61990fe',
			'label' => 'Particles',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ee1ff9c0c0df',
			'label' => 'Particles',
			'name' => 'section_particles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5ee1ffb80c0e0',
					'label' => 'Image',
					'name' => 'particle_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_5ee1ff9c0c0df',
				),
				array(
					'key' => 'field_5ee1ffd30c0e1',
					'label' => 'Custom Class',
					'name' => 'particle_custom_class',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5ee1ff9c0c0df',
				),
				array(
					'key' => 'field_5ee200310c0e4',
					'label' => 'Animation Name',
					'name' => 'particle_animation_name',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'vlt-fade-in-left' => 'Fade In Left',
						'vlt-fade-in-right' => 'Fade In Right',
						'vlt-fade-in-left vlt-fade-in-left--small' => 'Fade In Left (Small)',
						'vlt-fade-in-right vlt-fade-in-right--small' => 'Fade In Right (Small)',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 1,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_5ee1ff9c0c0df',
				),
				array(
					'key' => 'field_5ee1fff50c0e2',
					'label' => 'Transition Duration',
					'name' => 'particle_transition_duration',
					'aria-label' => '',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 10,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_5ee1ff9c0c0df',
				),
				array(
					'key' => 'field_5ee200c00c0e6',
					'label' => 'Transition Delay',
					'name' => 'particle_transition_delay',
					'aria-label' => '',
					'type' => 'range',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 0,
					'max' => 10,
					'step' => '0.1',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_5ee1ff9c0c0df',
				),
			),
		),
		array(
			'key' => 'field_644ce99ca3e42',
			'label' => 'Circles',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_644ce9aaa3e43',
			'label' => 'Circles',
			'name' => 'section_circles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_644ce9d1a3e44',
					'label' => 'Size',
					'name' => 'circle_size',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'small' => 'Small',
						'large' => 'Large',
					),
					'default_value' => 'small',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_644ce9aaa3e43',
				),
				array(
					'key' => 'field_644ce9f9a3e45',
					'label' => 'Position',
					'name' => 'circle_position',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'top-left' => 'Top Left',
						'bottom-left' => 'Bottom Left',
						'top-right' => 'Top Right',
						'bottom-right' => 'Bottom Right',
						'custom' => 'Custom',
					),
					'default_value' => 'top-right',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_644ce9aaa3e43',
				),
				array(
					'key' => 'field_66e026cf1bd53',
					'label' => 'Custom Class',
					'name' => 'circle_custom_class',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_644ce9aaa3e43',
				),
				array(
					'key' => 'field_644ceb56bf119',
					'label' => 'Absolute',
					'name' => 'circle_absolute',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'ui' => 1,
					'parent_repeater' => 'field_644ce9aaa3e43',
				),
			),
		),
		array(
			'key' => 'field_644cef4e64fbe',
			'label' => 'Overlay',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_644cef6864fbf',
			'label' => 'Overlay',
			'name' => 'section_overlay',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => 'radial-gradient(50% 50% at 50% 50%, transparent 0%, var(--vlt-color-light-black-0p5) 100%), linear-gradient(0deg, var(--vlt-color-light-black-0p5), var(--vlt-color-light-black-0p5))',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'fullpage-slide',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_66dc5d57001fd',
	'title' => '[Widget] About',
	'fields' => array(
		array(
			'key' => 'field_66dc5d57012fe',
			'label' => 'Logo',
			'name' => 'about_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_66dc5eaa5ef26',
			'label' => 'Logo Height',
			'name' => 'about_logo_height',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66dc5d57012fe',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 32,
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => 'px',
		),
		array(
			'key' => 'field_66dc5d840b3ff',
			'label' => 'Title',
			'name' => 'about_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66dc5d940b400',
			'label' => 'Description',
			'name' => 'about_description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'widget',
				'operator' => '==',
				'value' => 'vlthemes_widget_about',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'modified' => 1725718301,
) );

	acf_add_local_field_group( array(
	'key' => 'group_59be47f52a277',
	'title' => '[Widget] Popular Posts',
	'fields' => array(
		array(
			'key' => 'field_59be47f52d5c0',
			'label' => 'Number of Posts',
			'name' => 'popular_posts_number_of_posts',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5eeddf9c781fc',
			'label' => 'Layout',
			'name' => 'popular_posts_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'list' => 'List',
				'slider' => 'Slider',
			),
			'default_value' => 'list',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'widget',
				'operator' => '==',
				'value' => 'vlthemes_widget_popular_posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => 1592647639,
) );

	acf_add_local_field_group( array(
	'key' => 'group_59be4075bbab4',
	'title' => '[Widget] Recent Posts',
	'fields' => array(
		array(
			'key' => 'field_59be408062a67',
			'label' => 'Number of Posts',
			'name' => 'recent_posts_number_of_posts',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5eeddf4d6efb4',
			'label' => 'Layout',
			'name' => 'recent_posts_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'list' => 'List',
				'slider' => 'Slider',
			),
			'default_value' => 'list',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'widget',
				'operator' => '==',
				'value' => 'vlthemes_widget_recent_posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => 1592647646,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f3bb2f47e2af',
	'title' => '[Widget] Socials',
	'fields' => array(
		array(
			'key' => 'field_5f3bb30fe29be',
			'label' => 'Social Style',
			'name' => 'social_style',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style-1' => 'Style 1',
				'style-2' => 'Style 2',
				'style-3' => 'Style 3',
			),
			'default_value' => 'style-1',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f3bb37ee29bf',
			'label' => 'Social List',
			'name' => 'social_list',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_5f3bb3e9e29c2',
					'label' => 'Social URL',
					'name' => 'social_url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5f3bb37ee29bf',
				),
				array(
					'key' => 'field_5f3bb3bae29c0',
					'label' => 'Social Text',
					'name' => 'social_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f3bb30fe29be',
								'operator' => '==',
								'value' => 'style-1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5f3bb37ee29bf',
				),
				array(
					'key' => 'field_5f3bb3f4e29c3',
					'label' => 'Social Icon',
					'name' => 'social_icon',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f3bb30fe29be',
								'operator' => '==',
								'value' => 'style-2',
							),
						),
						array(
							array(
								'field' => 'field_5f3bb30fe29be',
								'operator' => '==',
								'value' => 'style-3',
							),
						),
						array(
							array(
								'field' => 'field_5f3bb30fe29be',
								'operator' => '==',
								'value' => 'style-4',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'socicon-internet' => 'Internet',
						'socicon-moddb' => 'Moddb',
						'socicon-indiedb' => 'Indiedb',
						'socicon-traxsource' => 'Traxsource',
						'socicon-gamefor' => 'Gamefor',
						'socicon-pixiv' => 'Pixiv',
						'socicon-myanimelist' => 'Myanimelist',
						'socicon-blackberry' => 'Blackberry',
						'socicon-wickr' => 'Wickr',
						'socicon-spip' => 'Spip',
						'socicon-napster' => 'Napster',
						'socicon-beatport' => 'Beatport',
						'socicon-hackerone' => 'Hackerone',
						'socicon-hackernews' => 'Hackernews',
						'socicon-smashwords' => 'Smashwords',
						'socicon-kobo' => 'Kobo',
						'socicon-bookbub' => 'Bookbub',
						'socicon-mailru' => 'Mailru',
						'socicon-gitlab' => 'Gitlab',
						'socicon-instructables' => 'Instructables',
						'socicon-portfolio' => 'Portfolio',
						'socicon-codered' => 'Codered',
						'socicon-origin' => 'Origin',
						'socicon-nextdoor' => 'Nextdoor',
						'socicon-udemy' => 'Udemy',
						'socicon-livemaster' => 'Livemaster',
						'socicon-crunchbase' => 'Crunchbase',
						'socicon-homefy' => 'Homefy',
						'socicon-calendly' => 'Calendly',
						'socicon-realtor' => 'Realtor',
						'socicon-tidal' => 'Tidal',
						'socicon-qobuz' => 'Qobuz',
						'socicon-natgeo' => 'Natgeo',
						'socicon-mastodon' => 'Mastodon',
						'socicon-unsplash' => 'Unsplash',
						'socicon-homeadvisor' => 'Homeadvisor',
						'socicon-angieslist' => 'Angieslist',
						'socicon-codepen' => 'Codepen',
						'socicon-slack' => 'Slack',
						'socicon-openaigym' => 'Openaigym',
						'socicon-logmein' => 'Logmein',
						'socicon-mergerr' => 'Mergerr',
						'socicon-gotomeeting' => 'Gotomeeting',
						'socicon-aliexpress' => 'Aliexpress',
						'socicon-guru' => 'Guru',
						'socicon-appstore' => 'Appstore',
						'socicon-homes' => 'Homes',
						'socicon-zoom' => 'Zoom',
						'socicon-alibaba' => 'Alibaba',
						'socicon-craigslist' => 'Craigslist',
						'socicon-wix' => 'Wix',
						'socicon-redfin' => 'Redfin',
						'socicon-googlecalendar' => 'Googlecalendar',
						'socicon-shopify' => 'Shopify',
						'socicon-freelancer' => 'Freelancer',
						'socicon-seedrs' => 'Seedrs',
						'socicon-bing' => 'Bing',
						'socicon-doodle' => 'Doodle',
						'socicon-bonanza' => 'Bonanza',
						'socicon-squarespace' => 'Squarespace',
						'socicon-toptal' => 'Toptal',
						'socicon-gust' => 'Gust',
						'socicon-ask' => 'Ask',
						'socicon-trulia' => 'Trulia',
						'socicon-loomly' => 'Loomly',
						'socicon-ghost' => 'Ghost',
						'socicon-upwork' => 'Upwork',
						'socicon-fundable' => 'Fundable',
						'socicon-booking' => 'Booking',
						'socicon-googlemaps' => 'Googlemaps',
						'socicon-zillow' => 'Zillow',
						'socicon-niconico' => 'Niconico',
						'socicon-toneden' => 'Toneden',
						'socicon-augment' => 'Augment',
						'socicon-bitbucket' => 'Bitbucket',
						'socicon-fyuse' => 'Fyuse',
						'socicon-yt-gaming' => 'Yt-gaming',
						'socicon-sketchfab' => 'Sketchfab',
						'socicon-mobcrush' => 'Mobcrush',
						'socicon-microsoft' => 'Microsoft',
						'socicon-pandora' => 'Pandora',
						'socicon-messenger' => 'Messenger',
						'socicon-gamewisp' => 'Gamewisp',
						'socicon-bloglovin' => 'Bloglovin',
						'socicon-tunein' => 'Tunein',
						'socicon-gamejolt' => 'Gamejolt',
						'socicon-trello' => 'Trello',
						'socicon-spreadshirt' => 'Spreadshirt',
						'socicon-500px' => '500px',
						'socicon-8tracks' => '8tracks',
						'socicon-airbnb' => 'Airbnb',
						'socicon-alliance' => 'Alliance',
						'socicon-amazon' => 'Amazon',
						'socicon-amplement' => 'Amplement',
						'socicon-android' => 'Android',
						'socicon-angellist' => 'Angellist',
						'socicon-apple' => 'Apple',
						'socicon-appnet' => 'Appnet',
						'socicon-baidu' => 'Baidu',
						'socicon-bandcamp' => 'Bandcamp',
						'socicon-battlenet' => 'Battlenet',
						'socicon-mixer' => 'Mixer',
						'socicon-bebee' => 'Bebee',
						'socicon-bebo' => 'Bebo',
						'socicon-behance' => 'Bēhance',
						'socicon-blizzard' => 'Blizzard',
						'socicon-blogger' => 'Blogger',
						'socicon-buffer' => 'Buffer',
						'socicon-chrome' => 'Chrome',
						'socicon-coderwall' => 'Coderwall',
						'socicon-curse' => 'Curse',
						'socicon-dailymotion' => 'Dailymotion',
						'socicon-deezer' => 'Deezer',
						'socicon-delicious' => 'Delicious',
						'socicon-deviantart' => 'Deviantart',
						'socicon-diablo' => 'Diablo',
						'socicon-digg' => 'Digg',
						'socicon-discord' => 'Discord',
						'socicon-disqus' => 'Disqus',
						'socicon-douban' => 'Douban',
						'socicon-draugiem' => 'Draugiem',
						'socicon-dribbble' => 'Dribbble',
						'socicon-drupal' => 'Drupal',
						'socicon-ebay' => 'Ebay',
						'socicon-ello' => 'Ello',
						'socicon-endomodo' => 'Endomodo',
						'socicon-envato' => 'Envato',
						'socicon-etsy' => 'Etsy',
						'socicon-facebook' => 'Facebook',
						'socicon-feedburner' => 'Feedburner',
						'socicon-filmweb' => 'Filmweb',
						'socicon-firefox' => 'Firefox',
						'socicon-flattr' => 'Flattr',
						'socicon-flickr' => 'Flickr',
						'socicon-formulr' => 'Formulr',
						'socicon-forrst' => 'Forrst',
						'socicon-foursquare' => 'Foursquare',
						'socicon-friendfeed' => 'Friendfeed',
						'socicon-github' => 'Github',
						'socicon-goodreads' => 'Goodreads',
						'socicon-google' => 'Google',
						'socicon-googlescholar' => 'Googlescholar',
						'socicon-googlegroups' => 'Googlegroups',
						'socicon-googlephotos' => 'Googlephotos',
						'socicon-googleplus' => 'Googleplus',
						'socicon-grooveshark' => 'Grooveshark',
						'socicon-hackerrank' => 'Hackerrank',
						'socicon-hearthstone' => 'Hearthstone',
						'socicon-hellocoton' => 'Hellocoton',
						'socicon-heroes' => 'Heroes',
						'socicon-smashcast' => 'Smashcast',
						'socicon-horde' => 'Horde',
						'socicon-houzz' => 'Houzz',
						'socicon-icq' => 'Icq',
						'socicon-identica' => 'Identica',
						'socicon-imdb' => 'Imdb',
						'socicon-instagram' => 'Instagram',
						'socicon-issuu' => 'Issuu',
						'socicon-istock' => 'Istock',
						'socicon-itunes' => 'Itunes',
						'socicon-keybase' => 'Keybase',
						'socicon-lanyrd' => 'Lanyrd',
						'socicon-lastfm' => 'Lastfm',
						'socicon-line' => 'Line',
						'socicon-linkedin' => 'Linkedin',
						'socicon-livejournal' => 'Livejournal',
						'socicon-lyft' => 'Lyft',
						'socicon-macos' => 'Macos',
						'socicon-mail' => 'Mail',
						'socicon-medium' => 'Medium',
						'socicon-meetup' => 'Meetup',
						'socicon-mixcloud' => 'Mixcloud',
						'socicon-modelmayhem' => 'Modelmayhem',
						'socicon-mumble' => 'Mumble',
						'socicon-myspace' => 'Myspace',
						'socicon-newsvine' => 'Newsvine',
						'socicon-nintendo' => 'Nintendo',
						'socicon-npm' => 'Npm',
						'socicon-odnoklassniki' => 'Odnoklassniki',
						'socicon-openid' => 'Openid',
						'socicon-opera' => 'Opera',
						'socicon-outlook' => 'Outlook',
						'socicon-overwatch' => 'Overwatch',
						'socicon-patreon' => 'Patreon',
						'socicon-paypal' => 'Paypal',
						'socicon-periscope' => 'Periscope',
						'socicon-persona' => 'Persona',
						'socicon-pinterest' => 'Pinterest',
						'socicon-play' => 'Play',
						'socicon-player' => 'Player',
						'socicon-playstation' => 'Playstation',
						'socicon-pocket' => 'Pocket',
						'socicon-qq' => 'Qq',
						'socicon-quora' => 'Quora',
						'socicon-raidcall' => 'Raidcall',
						'socicon-ravelry' => 'Ravelry',
						'socicon-reddit' => 'Reddit',
						'socicon-renren' => 'Renren',
						'socicon-researchgate' => 'Researchgate',
						'socicon-residentadvisor' => 'Residentadvisor',
						'socicon-reverbnation' => 'Reverbnation',
						'socicon-rss' => 'Rss',
						'socicon-sharethis' => 'Sharethis',
						'socicon-skype' => 'Skype',
						'socicon-slideshare' => 'Slideshare',
						'socicon-smugmug' => 'Smugmug',
						'socicon-snapchat' => 'Snapchat',
						'socicon-songkick' => 'Songkick',
						'socicon-soundcloud' => 'Soundcloud',
						'socicon-spotify' => 'Spotify',
						'socicon-stackexchange' => 'Stackexchange',
						'socicon-stackoverflow' => 'Stackoverflow',
						'socicon-starcraft' => 'Starcraft',
						'socicon-stayfriends' => 'Stayfriends',
						'socicon-steam' => 'Steam',
						'socicon-storehouse' => 'Storehouse',
						'socicon-strava' => 'Strava',
						'socicon-streamjar' => 'Streamjar',
						'socicon-stumbleupon' => 'Stumbleupon',
						'socicon-swarm' => 'Swarm',
						'socicon-teamspeak' => 'Teamspeak',
						'socicon-teamviewer' => 'Teamviewer',
						'socicon-technorati' => 'Technorati',
						'socicon-telegram' => 'Telegram',
						'socicon-tripadvisor' => 'Tripadvisor',
						'socicon-tripit' => 'Tripit',
						'socicon-triplej' => 'Triplej',
						'socicon-tumblr' => 'Tumblr',
						'socicon-twitch' => 'Twitch',
						'socicon-twitter' => 'Twitter',
						'socicon-uber' => 'Uber',
						'socicon-ventrilo' => 'Ventrilo',
						'socicon-viadeo' => 'Viadeo',
						'socicon-viber' => 'Viber',
						'socicon-viewbug' => 'Viewbug',
						'socicon-vimeo' => 'Vimeo',
						'socicon-vine' => 'Vine',
						'socicon-vkontakte' => 'Vkontakte',
						'socicon-warcraft' => 'Warcraft',
						'socicon-wechat' => 'Wechat',
						'socicon-weibo' => 'Weibo',
						'socicon-whatsapp' => 'Whatsapp',
						'socicon-wikipedia' => 'Wikipedia',
						'socicon-windows' => 'Windows',
						'socicon-wordpress' => 'Wordpress',
						'socicon-wykop' => 'Wykop',
						'socicon-xbox' => 'Xbox',
						'socicon-xing' => 'Xing',
						'socicon-yahoo' => 'Yahoo',
						'socicon-yammer' => 'Yammer',
						'socicon-yandex' => 'Yandex',
						'socicon-yelp' => 'Yelp',
						'socicon-younow' => 'Younow',
						'socicon-youtube' => 'Youtube',
						'socicon-zapier' => 'Zapier',
						'socicon-zerply' => 'Zerply',
						'socicon-zomato' => 'Zomato',
						'socicon-zynga' => 'Zynga',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_5f3bb37ee29bf',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'widget',
				'operator' => '==',
				'value' => 'vlthemes_widget_socials',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'modified' => 1708421649,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5a04b3395086a',
	'title' => '[Widget] Trending Posts',
	'fields' => array(
		array(
			'key' => 'field_5e47b6e79c7b5',
			'label' => 'Number of Posts',
			'name' => 'trending_posts_number_of_posts',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5eeddf96d3bf8',
			'label' => 'Layout',
			'name' => 'trending_posts_layout',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'list' => 'List',
				'slider' => 'Slider',
			),
			'default_value' => 'list',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'widget',
				'operator' => '==',
				'value' => 'vlthemes_widget_trending_posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
	'modified' => 1592647635,
) );
} );
